spring.application.name=UserManagement

# Copy this file to application.properties or set these values as environment variables.
spring.datasource.url=jdbc:mysql://localhost:3306/user_management
spring.datasource.username=your_database_username
spring.datasource.password=your_database_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
